<template>
    <v-container>
        <v-card-title>API Items</v-card-title>

        <v-card-text>
            <api-items url="https://api.restful-api.dev/objects" v-slot="props">
                <v-select label="Select" item-title="name" item-value="id" v-bind="props"></v-select>
            </api-items>

            <api-items url="https://api.restful-api.dev/objects" v-slot="props">
                <v-autocomplete label="Autocomplete" item-title="name" item-value="id" v-bind="props"></v-autocomplete>
            </api-items>

            <api-items url="https://api.restful-api.dev/objects" v-slot="props">
                <v-combobox label="Combobox" item-title="name" item-value="id" v-bind="props"></v-combobox>
            </api-items>

            <api-items url="https://api.restful-api.dev/objects/false-api" v-slot="props">
                <v-select label="Error" item-title="name" item-value="id" v-bind="props"></v-select>
            </api-items>
        </v-card-text>


    </v-container>
</template>
<script lang="ts" setup >
import crud from '../../src/runtime/components/crud.vue'

// Generated by https://quicktype.io

export interface Device {
    id: string;
    name: string;
    data: Data;
}

export interface Data {
    year: number;
    price: number;
    "CPU model": string;
    "Hard disk size": string;
}

const defaultItem: Device = {
    id: '',
    name: '',
    data: {
        year: 0,
        price: 0,
        "CPU model": '',
        "Hard disk size": ''
    }
}



const crudRef = ref<typeof crud | null>(null)
</script> 